version: "3.7"
services:
    database: 
        image: postgres:12-alpine
        container_name: ${DATABASE_CONTAINER_NAME}
        env_file: .env
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes: 
            - ./database:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    server:
        container_name: ${SERVER_CONTAINER_NAME}
        env_file: .env
        depends_on:
            - database
        build: 
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ".:/usr/src/app"
        ports: 
            - "3000:3000"